config/routes.rb
require 'sidekiq/web' if Rails.env.development?
Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'admin/home#xero'
  get 'auth/xero_oauth2/callback', to: 'admin/home#index'

  # get 'careers', to: 'careers#index'
  get 'contacts', to: 'contacts#index'
  get 'menu', to: 'menu#index'
  get 'products', to: 'products#index'
  get 'visit', to: 'visit#index'

  namespace :admin do
    get '/', to: 'home#index'
    get 'fulfillment', to: 'fulfillment#index'
    get 'delivery_route', to: 'delivery_route#index'
    post 'delivery_route', to: 'delivery_route#show'
    resources :contacts do
      member do
        get :undestroy
        get :repeat_last_order
      end
    end
    resources :notes do
      member do
        get 'close'
        patch 'resolve'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
      end
    end
    resources :products
    resources :sales_reps
    resources :states
    resources :towns
    resources :users

    get 'reports', to: 'reports#index'
    get 'reports/kegs', to: 'reports#kegs'
    get 'reports/orders', to: 'reports#orders'
  end

  namespace :customer do
    get '/', to: 'home#index'
    get '/signup', to: 'signup#new'
    post '/signup', to: 'signup#create'
    get '/orders/:id', to: 'orders#show', as: 'order'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include SoftDeletable
  include Xero::Syncable

  has_many :line_items, inverse_of: :order
  has_many :xero_sync_errors, as: :syncable
  belongs_to :contact
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User', optional: true
  belongs_to :assigned_to, class_name: 'User', optional: true
  accepts_nested_attributes_for :line_items, reject_if: :reject_line_items

  validates :contact_id, presence: true
  validates :delivery_date, presence: true

  after_commit :send_assigned_order_email

  scope :active, -> { where(fulfilled_on: nil, deleted_at: nil).order('delivery_date asc') }
  scope :fulfilled, -> { where.not(fulfilled_on: nil).order('fulfilled_on DESC') }
  scope :inactive, -> { where.not(deleted_at: nil) }
  scope :late, -> { active.where(delivery_date: ...Time.zone.today).order('delivery_date asc') }

  def self.to_be_fulfilled(day)
    if day == Time.zone.today
      Order.active.where(delivery_date: ..Time.zone.today)
    else
      Order.active.where(delivery_date: day)
    end
  end

  def self.display_all(show)
    display(Order.all, show)
  end

  def self.display(orders, show)
    case show
    when 'late'
      [orders.late, 'Late Orders']
    when 'fulfilled'
      [orders.fulfilled, 'Delivered Orders']
    when 'active'
      [orders.active, 'Active Orders']
    when 'void'
      [orders.inactive, 'Void Orders']
    else
      contact = Contact.find_by(id: show)
      [contact.orders.order('delivery_date DESC'), "Orders by #{contact.name}"]
    end
  end

  def contact_name
    contact&.name
  end

  def contact_name=(name)
    self.contact = Contact.find_by(name:)
  end

  def fulfilled?
    fulfilled_on != nil
  end

  def fulfill
    update(fulfilled_on: Time.zone.today)
  end

  def unfulfill
    update(fulfilled_on: nil)
  end

  private

  def send_assigned_order_email
    return if assigned_to.nil?

    OrderMailer.with(order: self).assigned.deliver_later
  end

  def reject_line_items(attributes)
    attributes['quantity'].blank? || attributes['product_id'].blank?
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy, :undestroy]
    before_action :set_xero_invoice_url, only: [:show, :edit, :index]
    before_action :must_be_admin

    def index
      @orders, @title = Order.display_all(params[:show] || 'active')
      @show           = params[:show]
    end

    def invoice
      @order = Order.find(params[:id])
      sync_to_xero(@order.contact, Xero::Contact)
      sync_to_xero(@order, Xero::Invoice) unless @order.synced?

      path = admin_order_path(@order)
      path = edit_admin_order_path(@order) if @order.reload.xero_sync_errors.any?

      redirect_to path
    end

    def show; end

    def new
      @order            = Order.new
      @order.line_items = [
        LineItem.new,
        LineItem.new,
        LineItem.new,
        LineItem.new,
        LineItem.new,
        LineItem.new,
        LineItem.new,
        LineItem.new,
        LineItem.new,
        LineItem.new
      ]
    end

    def edit
      redirect_to admin_order_path(@order) if @order.fulfilled? || @order.synced?
    end

    def create
      @order = Order.new(order_params.merge(created_by: current_user))

      respond_to do |format|
        if @order.save
          format.html { redirect_to path, notice: 'Order was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @order.update(order_params.merge(updated_by: current_user))
          format.html { redirect_to path, notice: 'Order was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def fulfill
      @order = Order.find(params[:id])
      @order.fulfill

      respond_to do |format|
        if @order.save
          format.html do
            redirect_to admin_orders_path,
                        notice: 'Order was successfully delivered. <br /><br />' \
                                "<a href=\"/admin/orders/#{@order.id}\">View Order</a>"
          end
        else
          format.html { redirect_to admin_orders_path, notice: 'Error' }
        end
      end
    end

    def unfulfill
      @order = Order.find(params[:id])
      @order.unfulfill

      respond_to do |format|
        if @order.save
          format.html { redirect_to edit_admin_order_path(@order), notice: 'Order was successfully undelivered.' }
        else
          format.html { redirect_to admin_order_path(@order), notice: 'Error' }
        end
      end
    end

    def destroy
      notice = @order.destroy
      respond_to do |format|
        format.html { redirect_to admin_orders_path, notice: "Order was successfully #{notice}." }
      end
    end

    def undestroy
      @order.undestroy
      respond_to do |format|
        format.html { redirect_to admin_orders_path, notice: 'Order was made active.' }
      end
    end

    private

    def set_order
      @order = Order.find(params[:id])
    end

    def set_xero_invoice_url
      @xero_invoice_url = 'https://go.xero.com/AccountsReceivable/View.aspx?InvoiceID='
    end

    def path
      params[:save] ? admin_orders_url : edit_admin_order_url(@order)
    end

    def order_params
      params.expect(
        order: [:assigned_to_id,
                :comments,
                :contact_name,
                :created_by_id,
                :customer_po,
                :delivery_date,
                :updated_by_id,
                { line_items_attributes: [
                  :fulfilled,
                  :id,
                  :product_id,
                  :quantity,
                  :_destroy
                ] }]
      )
    end
  end
end

app/controllers/customer/orders_controller.rb
module Customer
  class OrdersController < ApplicationController
    before_action :must_be_customer

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/views/admin/orders/_contact.html.erb
<legend>
  <%= link_to contact.name, edit_admin_contact_path(contact) %>
</legend>

<div style="float:right;">
  <%= link_to "View all orders by #{contact.name}", admin_orders_path({ show: contact.id }) %> |
  <%= link_to 'View on map', Google::Maps.query_url(contact.full_address), target: '_blank' %>
</div>

<p>
  Pickup Check: <strong><%= contact.pickup_check ? 'Yes' : 'No' -%></strong>
</p>

<p>
  Paperless Billing: <strong><%= contact.paperless_billing ? 'Yes' : 'No' -%></strong>
</p>

<% unless contact.phone.blank? -%>
  <p>
    Phone: <strong><%= contact.phone %></strong>
  </p>
<% end -%>

<% unless contact.email.blank? -%>
  <p>
    Email: <strong><%= link_to contact.email, "mailto:" + contact.email, target: "_blank" %></strong>
  </p>
<% end -%>

<p>
  Address:
  <% unless contact.address.blank? -%>
    <strong><%= contact.address %>,</strong>
  <% end -%>
  <strong><%= contact.town.name %></strong>
</p>

<p>
  <%= contact.description %>
</p>

app/views/admin/orders/_form.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :contact_name, 'Contact' %>
  <%= f.text_field :contact_name, list: 'contacts' %>

  <datalist id="contacts">
    <% Contact.active.each do |contact| %>
      <option value="<%= contact.name %>">
    <% end %>
  </datalist>
</div>

<div class="field">
  <%= f.label :delivery_date %>

  <%= f.date_field :delivery_date, class: "datepicker", value: @order.delivery_date %>
</div>

<div class="field">
  <%= f.label :assigned_to, 'Assigned To' %>
  <%= f.collection_select :assigned_to_id, User.admins.order(:name), :id, :name, include_blank: true %>
</div>

<div class="field">
  <%= f.label :customer_po, "Customer PO" %>
  <%= f.text_field :customer_po %>
</div>

<h3>Line Items</h3>

<div id="line_items">
  <%= f.fields_for :line_items do |line_item| %>
    <%= render 'line_item_fields', f: line_item %>
  <% end -%>
</div>

<div class="field">
  <%= f.label :comments, 'Public Comments' %><br/>
  <%= f.text_area :comments, rows: 5, cols: 50 %>
</div>

app/views/admin/orders/_line_item_fields.html.erb
<div class="nested-fields">
  <span class="field">
    <%= f.number_field :quantity, min: 1 %>
  </span>
  <span class="field">
    <% f.label :product_id %>
    <%= f.collection_select(:product_id,
                            Product.in_production.order("name ASC"),
                            :id,
                            :name,
                            {prompt: "Select Product"})
    %>
  </span>
</div>

app/views/admin/orders/_order_table.html.erb
<tr class="<%= cycle "even", "odd" %>">
  <td><strong><%= order.id.to_s %></strong></td>
  <td>
    <%= order.assigned_to&.name %>
  </td>
  <% if order.fulfilled? || order.synced? -%>
    <td><%= link_to order.contact.name, admin_order_path(order) %></td>
  <% else -%>
    <td><%= link_to order.contact.name, edit_admin_order_path(order) %></td>
  <% end -%>
  <td class=<%= order.delivery_date < Time.zone.today && !order.fulfilled? ? 'late' : '' %>>
    <% if order.fulfilled? -%>
      <%= humanize_date order.fulfilled_on %>
    <% else -%>
      <%= humanize_date order.delivery_date %>
    <% end -%>
  </td>
  <td><%= order.contact.town.name %></td>
  <td>
    <% if order.synced? -%>
      <%= link_to 'Open Invoice', @xero_invoice_url + order.xero_id, target: "_blank" %>
    <% end -%>
  </td>
  <% if order.fulfilled? -%>
    <td></td>
    <td></td>
  <% else -%>
    <td><%= link_to 'Deliver', fulfill_admin_order_path(order), id: "deliver_#{order.id}" %></td>
    <td>
      <%= link_to 'Void', admin_order_path(order), confirm: 'Are you sure?', method: :delete, id: "void_#{order.id}" %>
    </td>
  <% end -%>
</tr>

app/views/admin/orders/_table_head.html.erb
<tr class="title">
  <th>PO</th>
  <th>Assigned To</th>
  <th>Business</th>
  <th>
    <% if @show == "fulfilled" -%>
      Fulfilled On
    <% else -%>
      Delivery Date
    <% end -%>
  </th>
  <th>Town</th>
  <th></th>
  <th></th>
  <th></th>
</tr>

app/views/admin/orders/edit.html.erb
<h1>PO <%= @order.id %></h1>

<table>
  <% if @order.assigned_to -%>
    <tr>
      <td>
        Assigned to <strong><%= @order.assigned_to&.name %></strong>
      </td>
    </tr>
  <% end -%>
  <tr>
    <td>
      Created by <strong><%= @order.created_by&.name %></strong> on <%= humanize_date @order.created_at %>.
    </td>
  </tr>
  <% if @order.updated_by -%>
    <tr>
      <td>
        Updated by <strong><%= @order.updated_by&.name %></strong> on <%= humanize_date @order.updated_at %>.
      </td>
    </tr>
  <% end -%>
</table>

<%= form_for(@order, url: admin_order_path(@order), html: { autocomplete: 'off' }) do |f| %>

  <p>
    <%= link_to 'Create Invoice', invoice_admin_order_path(@order) %> |
    <%= link_to 'Mark Delivered', fulfill_admin_order_path(@order) %> |
    <%= link_to 'Void', admin_order_path(@order), confirm: 'Are you sure?', method: :delete %>
  </p>


  <p class="actions">
    <%= f.submit 'Update', name: :update, disable_with: "Loading..." %>
    <%= f.submit 'Save & Finish', name: :save, disable_with: "Loading..." %>
    <%= link_to 'Cancel', admin_orders_path %>
  </p>

  <% unless @order.xero_sync_errors.empty? -%>
    <div class="xero_errors">
      <h3>Xero Sync Errors:</h3>
      <ul>
        <% @order.xero_sync_errors.each do |error| -%>
          <li><%= error.message %></li>
        <% end -%>
      </ul>
    </div>
  <% end -%>

  <div class="wide-wrapper">
    <fieldset class="column">
      <legend>Order <%= @order.id %></legend>
      <%= render partial: 'form', locals: { f: f } %>

      <p class="actions">
        <%= f.submit 'Update', name: :update, disable_with: "Loading..." %>
        <%= f.submit 'Save & Finish', name: :save, disable_with: "Loading..." %>
        <%= link_to 'Cancel', admin_orders_path %>
      </p>
    </fieldset>
<% end -%>

<fieldset class="column">
  <%= render partial: 'contact', locals: { contact: @order.contact } %>
</fieldset>
</div>

app/views/admin/orders/index.html.erb
<h1><%= @title %></h1>

<p>
  <%= link_to 'New Order', new_admin_order_path %> |
  <%= link_to "Create a Delivery Route", admin_delivery_route_path %>
</p>

<p>
  <%= link_to 'Active Orders', admin_orders_path({show: "active"}) %> |
  <%= link_to 'Delivered Orders', admin_orders_path({show: "fulfilled"}) %> |
  <%= link_to 'Late Orders', admin_orders_path({show: "late"}) %> |
  <%= link_to 'Voided Orders', admin_orders_path({show: "void"}) %>
</p>

<div class="wide-wrapper">
  <table class="crud">
    <%= render "table_head" %>
    <% @orders.each do |order| -%>
      <%= render "order_table", order: order %>
    <% end -%>
  </table>
</div>

<br/>

app/views/admin/orders/new.html.erb
<h1>New order</h1>

<%= form_for(@order, url: admin_orders_path, html: { autocomplete: 'off' }) do |f| -%>
  <p class="actions">
    <%= f.submit 'Update', name: :update, disable_with: "Loading..." %>
    <%= f.submit 'Save & Finish', name: :save, disable_with: "Loading..." %>
    <%= link_to 'Cancel', admin_orders_path %>
  </p>
  <%= render partial: 'form', locals: {f: f} %>
<% end -%>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<h1><%= @order.contact.name %></h1>

<table>
  <% if @order.assigned_to -%>
    <tr>
      <td>
        Assigned to <strong><%= @order.assigned_to&.name %></strong>
      </td>
    </tr>
  <% end -%>
  <tr>
    <td>
      Created by <strong><%= @order.created_by&.name %></strong> on <%= humanize_date @order.created_at %>.
    </td>
  </tr>
  <% if @order.updated_by -%>
    <tr>
      <td>
        Updated by <strong><%= @order.updated_by&.name %></strong> on <%= humanize_date @order.updated_at %>.
      </td>
    </tr>
  <% end -%>
</table>

<% if @order.fulfilled_on -%>
  <h2>Delivered on <%= humanize_date @order.fulfilled_on %></h2>
  <p>
    <% if @order.synced? -%>
      <%= link_to 'Open Invoice', @xero_invoice_url + @order.xero_id, target: "_blank" %> |
    <% else -%>
      <%= link_to 'Create Invoice', invoice_admin_order_path(@order) %> |
    <% end -%>
    <%= link_to 'Undeliver', unfulfill_admin_order_path(@order) %>
  </p>
<% else -%>
  <p>
    <% if @order.synced? -%>
      <%= link_to 'Open Invoice', @xero_invoice_url + @order.xero_id, target: "_blank" %> |
    <% else -%>
      <%= link_to 'Create Invoice', invoice_admin_order_path(@order) %> |
    <% end -%>
    <%= link_to 'Mark Delivered', fulfill_admin_order_path(@order) %> |
    <%= link_to 'Void', admin_order_path(@order), confirm: 'Are you sure?', method: :delete %>
  </p>
<% end %>

<fieldset class="column">
  <legend>Order #<%= @order.id %></legend>

  <table class="crud">
    <tr class="title">
      <th>Quantity</th>
      <th>Product</th>
    </tr>

    <% @order.line_items.each do |line_item| -%>
      <tr class="<%= cycle "even", "odd" %>">
        <td style="white-space: nowrap"><%= line_item.quantity %></td>
        <td style="white-space: nowrap"><%= line_item.product.name %></td>
      </tr>
    <% end -%>
  </table>

  <p><%= @order.comments %></p>
</fieldset>

<fieldset class="column">
  <%= render partial: 'contact', locals: { contact: @order.contact } %>
</fieldset>