config/routes.rb
require 'sidekiq/web' if Rails.env.development?
Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'admin/home#xero'
  get 'auth/xero_oauth2/callback', to: 'admin/home#index'

  # get 'careers', to: 'careers#index'
  get 'contacts', to: 'contacts#index'
  get 'menu', to: 'menu#index'
  get 'products', to: 'products#index'
  get 'visit', to: 'visit#index'

  namespace :admin do
    get '/', to: 'home#index'
    get 'fulfillment', to: 'fulfillment#index'
    get 'delivery_route', to: 'delivery_route#index'
    post 'delivery_route', to: 'delivery_route#show'
    resources :contacts do
      member do
        get :undestroy
        get :repeat_last_order
      end
    end
    resources :notes do
      member do
        get 'close'
        patch 'resolve'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
      end
    end
    resources :products
    resources :sales_reps
    resources :states
    resources :towns
    resources :users

    get 'reports', to: 'reports#index'
    get 'reports/kegs', to: 'reports#kegs'
    get 'reports/orders', to: 'reports#orders'
  end

  namespace :customer do
    get '/', to: 'home#index'
    get '/signup', to: 'signup#new'
    post '/signup', to: 'signup#create'
    get '/orders/:id', to: 'orders#show', as: 'order'
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ApplicationController
    before_action :must_be_admin

    def index
      @late_orders     = Order.late.count
      @orders          = Order.active.count
      @todays_orders   = Order.to_be_fulfilled(Time.zone.today).count
      @contacts        = Contact.active.count
      @urgent_contacts = Contact.urgent.count
      @sales_reps      = SalesRep.count
      @states          = State.count
      @towns           = Town.count
      @products        = Product.count
      @active_products = Product.where(is_public: true).count
    end

    def xero
      auth_hash = request.env['omniauth.auth']

      current_user.update(
        xeroUid: auth_hash['uid'],
        xeroAccessToken: auth_hash['credentials']['token'],
        xeroRefreshToken: auth_hash['credentials']['refresh_token'],
        xeroTenantId: auth_hash['extra']['xero_tenants'][0]['tenantId'],
        xeroTokenExpiresAt: auth_hash['credentials']['expires_at']
      )

      redirect_to '/admin', notice: 'Xero Connected!'
    end
  end
end

app/controllers/customer/home_controller.rb
module Customer
  class HomeController < ApplicationController
    before_action :must_be_customer

    def index
      @orders = current_user.contact.orders.where(deleted_at: nil).order('id desc') if current_user.customer_activated?
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/admin/home/index.html.erb
<h1>Administration</h1>
<% unless current_user.xero_connected? -%>
  <p>
    <%= form_tag('/auth/xero_oauth2', method: 'post') do %>
      <button type='submit'>Connect to Xero</button>
    <% end %>
  </p>
<% end -%>

<% if Rails.env == 'development' -%>
  <p>
    <%= link_to 'Mailers', 'rails/mailers', target: '_blank' %>
  </p>
<% end -%>

<div class="wide-wrapper">
  <div class="c-panel">
    <fieldset>
      <legend><%= link_to "Orders", admin_orders_path %></legend>
      <ul>
        <li>
          <%= link_to "New Order", new_admin_order_path %>
        </li>
        <li>
          <%= link_to "Create a Delivery Route", admin_delivery_route_path %>
        </li>
        <li>&nbsp;</li>
      </ul>
      <ul>
        <% unless @late_orders.size == 0 -%>
          <li class="urgent">
            <%= link_to "#{@late_orders} late", admin_orders_path(show: :late) %>
          </li>
        <% end -%>
        <li>
          <%= link_to "#{@todays_orders} to fulfill today", admin_orders_path %>
        </li>
        <li>
          <%= link_to "#{@orders} in total", admin_orders_path %>
        </li>
      </ul>
    </fieldset>

    <fieldset>
      <legend><%= link_to "Contacts", admin_contacts_path %></legend>
      <ul>
        <li>
          <%= link_to 'New Contact', new_admin_contact_path %>
        </li>
        <% unless @urgent_contacts.size == 0 -%>
          <li class="urgent">
            <%= link_to "#{@urgent_contacts} urgent contacts", admin_contacts_path(show: :urgent) %>
          </li>
        <% end -%>
        <li>
          <%= pluralize @contacts, 'contact' %>
        </li>
      </ul>
    </fieldset>

    <fieldset>
      <legend><%= link_to "Products", admin_products_path %></legend>
      <ul>
        <li>
          <%= link_to 'New Product', new_admin_product_path %>
        </li>
        <li>
          <%= pluralize @products, 'product' %>
        </li>
        <li>
          <%= @active_products %> active products
        </li>
      </ul>
    </fieldset>

    <fieldset>
      <legend><%= link_to "Sales Reps", admin_sales_reps_path %></legend>
      <ul>
        <li>
          <%= link_to 'New Sales Rep', new_admin_sales_rep_path %>
        </li>
        <li>
          <%= pluralize @sales_reps, 'sales rep' %>
        </li>
      </ul>
    </fieldset>

    <fieldset>
      <legend><%= link_to "Locations", admin_states_path %></legend>
      <ul>
        <li>
          <%= link_to 'New State', new_admin_state_path %>
        </li>
        <li>
          <%= link_to 'View States', admin_states_path %>
        </li>
        <li>
          <%= pluralize @states, 'State' %>
        </li>
      </ul>
      <ul>
        <li>
          <%= link_to 'New Town', new_admin_town_path %>
        </li>
        <li>
          <%= link_to 'View Towns', admin_towns_path %>
        </li>
        <li>
          <%= pluralize @towns, 'Town' %>
        </li>
      </ul>
    </fieldset>

    <fieldset>
      <legend><%= link_to "Reports", admin_reports_path %></legend>
      <ul>
        <!--        <li>-->
        <%#= link_to 'Keg Report', admin_reports_kegs_path %>
        <!--        </li>-->
        <li>
          <%= link_to 'Wholesale Orders Report', admin_reports_orders_path %>
        </li>
      </ul>
    </fieldset>
  </div>
</div>