config/routes.rb
require 'sidekiq/web' if Rails.env.development?
Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'admin/home#xero'
  get 'auth/xero_oauth2/callback', to: 'admin/home#index'

  # get 'careers', to: 'careers#index'
  get 'contacts', to: 'contacts#index'
  get 'menu', to: 'menu#index'
  get 'products', to: 'products#index'
  get 'visit', to: 'visit#index'

  namespace :admin do
    get '/', to: 'home#index'
    get 'fulfillment', to: 'fulfillment#index'
    get 'delivery_route', to: 'delivery_route#index'
    post 'delivery_route', to: 'delivery_route#show'
    resources :contacts do
      member do
        get :undestroy
        get :repeat_last_order
      end
    end
    resources :notes do
      member do
        get 'close'
        patch 'resolve'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
      end
    end
    resources :products
    resources :sales_reps
    resources :states
    resources :towns
    resources :users

    get 'reports', to: 'reports#index'
    get 'reports/kegs', to: 'reports#kegs'
    get 'reports/orders', to: 'reports#orders'
  end

  namespace :customer do
    get '/', to: 'home#index'
    get '/signup', to: 'signup#new'
    post '/signup', to: 'signup#create'
    get '/orders/:id', to: 'orders#show', as: 'order'
  end
end

app/models/sales_rep.rb
class SalesRep < ApplicationRecord
  has_many :contacts

  validates :name, presence: true
end

app/controllers/admin/sales_reps_controller.rb
module Admin
  class SalesRepsController < ApplicationController
    before_action :set_sales_rep, only: [:edit, :update, :destroy]
    before_action :must_be_admin

    def index
      @sales_reps = SalesRep.order('sales_reps.name')
    end

    def show; end

    def new
      @sales_rep = SalesRep.new
    end

    def edit; end

    def create
      @sales_rep = SalesRep.new(sales_rep_params)

      respond_to do |format|
        if @sales_rep.save
          format.html { redirect_to admin_sales_reps_path, notice: 'SalesRep was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @sales_rep.update(sales_rep_params)
          format.html { redirect_to admin_sales_reps_path, notice: 'SalesRep was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @sales_rep.destroy
      respond_to do |format|
        format.html { redirect_to admin_sales_reps_path, notice: 'SalesRep was successfully destroyed.' }
      end
    end

    private

    def set_sales_rep
      @sales_rep = SalesRep.find(params[:id])
    end

    def sales_rep_params
      params.expect(sales_rep: [:email, :name, :phone])
    end
  end
end

app/views/admin/sales_reps/_form.html.erb
<% if sales_rep.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(sales_rep.errors.count, "error") %> prohibited this sales_rep from being saved:</h2>

    <ul>
      <% sales_rep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :name, autofocus: 'autofocus' %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :email %>
  <%= form.text_field :email %>
</div>

<div class="field">
  <%= form.label :phone %>
  <%= form.text_field :phone %>
</div>

<div class="actions">
  <%= form.submit %>
</div>

app/views/admin/sales_reps/edit.html.erb
<h1>Editing <%= @sales_rep.name %></h1>

<%= form_for(@sales_rep, url: admin_sales_rep_path(@sales_rep), html: { multipart: true, autocomplete: 'off' }) do |form| %>
  <%= render 'form', sales_rep: @sales_rep, form: form %>
<% end -%>

<br />
<h2>Contacts</h2>
<table class="crud">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>
  </thead>
  <% @sales_rep.contacts.each do |contact| -%>
    <tr>
      <td><%= link_to contact.name, edit_admin_contact_path(contact) %></td>
      <td><%= contact.email %></td>
    </tr>
  <% end -%>
</table>
<br />

<%= link_to 'Back', admin_sales_reps_path %>

app/views/admin/sales_reps/index.html.erb
<h1>Sales Reps</h1>

<p>
  <%= link_to 'New Sales Rep', new_admin_sales_rep_path %>
</p>

<div class="wide-wrapper">
  <table class="crud">
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @sales_reps.each do |sales_rep| %>
      <tr class="<%= cycle "even", "odd" %>">
        <td><%= link_to sales_rep.name, edit_admin_sales_rep_path(sales_rep) %></td>
        <td><%= sales_rep.email %></td>
        <td><%= sales_rep.phone %></td>
        <td>
          <%= link_to 'X', admin_sales_rep_path(sales_rep), method: :delete, id: "delete_#{sales_rep.id}", data: { confirm: 'Are you sure?' } %>
          &nbsp;
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br/>

app/views/admin/sales_reps/new.html.erb
<h1>New Sales Rep</h1>

<%= form_for(@sales_rep, url: admin_sales_reps_path, html: { multipart: true, autocomplete: 'off' }) do |form| -%>
  <%= render 'form', sales_rep: @sales_rep, form: form %>
<% end -%>

<%= link_to 'Back', admin_sales_reps_path %>