config/routes.rb
require 'sidekiq/web' if Rails.env.development?
Rails.application.routes.draw do
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'admin/home#xero'
  get 'auth/xero_oauth2/callback', to: 'admin/home#index'

  # get 'careers', to: 'careers#index'
  get 'contacts', to: 'contacts#index'
  get 'menu', to: 'menu#index'
  get 'products', to: 'products#index'
  get 'visit', to: 'visit#index'

  namespace :admin do
    get '/', to: 'home#index'
    get 'fulfillment', to: 'fulfillment#index'
    get 'delivery_route', to: 'delivery_route#index'
    post 'delivery_route', to: 'delivery_route#show'
    resources :contacts do
      member do
        get :undestroy
        get :repeat_last_order
      end
    end
    resources :notes do
      member do
        get 'close'
        patch 'resolve'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
      end
    end
    resources :products
    resources :sales_reps
    resources :states
    resources :towns
    resources :users

    get 'reports', to: 'reports#index'
    get 'reports/kegs', to: 'reports#kegs'
    get 'reports/orders', to: 'reports#orders'
  end

  namespace :customer do
    get '/', to: 'home#index'
    get '/signup', to: 'signup#new'
    post '/signup', to: 'signup#create'
    get '/orders/:id', to: 'orders#show', as: 'order'
  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :towns

  validates :name, presence: true
  validates :abbreviation, presence: true
end

app/controllers/admin/states_controller.rb
module Admin
  class StatesController < ApplicationController
    before_action :set_state, only: [:edit, :update, :destroy]
    before_action :must_be_admin

    def index
      @states = State.order(:name)
    end

    def new
      @state = State.new
    end

    def edit; end

    def create
      @state = State.new(state_params)

      respond_to do |format|
        if @state.save
          format.html { redirect_to admin_states_path, notice: 'State was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @state.update(state_params)
          format.html { redirect_to admin_states_path, notice: 'State was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @state.destroy
      respond_to do |format|
        format.html { redirect_to admin_states_path, notice: 'State was successfully destroyed.' }
      end
    end

    private

    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.expect(state: [:name, :abbreviation])
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/admin/states/_form.html.erb
<% if state.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

    <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :name, autofocus: 'autofocus' %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :abbreviation %>
  <%= form.text_field :abbreviation %>
</div>

<div class="actions">
  <%= form.submit %>
</div>

app/views/admin/states/edit.html.erb
<h1>Editing <%= @state.name %></h1>

<%= form_for(@state, url: admin_state_path(@state), html: { multipart: true, autocomplete: 'off' }) do |form| %>
  <%= render 'form', state: @state, form: form %>
<% end -%>

<%= link_to 'Back', admin_states_path %>

app/views/admin/states/index.html.erb
<h1>States</h1>

<p>
  <%= link_to 'New State', new_admin_state_path %>
</p>

<div class="wide-wrapper">
  <table class="crud">
    <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= link_to state.name, edit_admin_state_path(state) %></td>
        <td>
          <%= link_to 'X', admin_state_path(state), method: :delete, id: "delete_#{state.id}", data: { confirm: 'Are you sure?' } %>
          &nbsp;
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br/>

app/views/admin/states/new.html.erb
<h1>New State</h1>

<%= form_for(@state, url: admin_states_path, html: { multipart: true, autocomplete: 'off' }) do |form| -%>
  <%= render 'form', state: @state, form: form %>
<% end -%>

<%= link_to 'Back', admin_states_path %>